=== pprados/jndi-resources/trunk/jndi-resources/jndi-resources-cmd-line/src/main/templates/tools/xsd/jndi-resources.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
 * Copyright 2008 Philippe Prados.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
-->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.jndi-resources.org/1.0/"
	xmlns:tns="http://www.jndi-resources.org/1.0/"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<element name="resources">
		<annotation>
				<documentation xml:lang="en">Describe JNDI resources.</documentation>
				<documentation xml:lang="fr">Description des ressources JNDI.</documentation>
		</annotation>
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:resource" />
				<element ref="tns:comment" />
				<any processContents="strict" namespace="##other" />
			</choice>
			<attribute name="id" type="ID" />
			<anyAttribute processContents="strict" />
		</complexType>
	</element>

	<element name="resource">
		<annotation>
				<documentation xml:lang="en">Describe one JNDI resource.</documentation>
				<documentation xml:lang="fr">Description d'une ressource JNDI.</documentation>
		</annotation>
		<complexType>
			<sequence>
				<choice minOccurs="0" maxOccurs="unbounded">
					<element ref="tns:property" />
					<element ref="tns:comment" />
					<any processContents="skip" namespace="##other" />
				</choice>
				<choice minOccurs="0" maxOccurs="unbounded">
					<element ref="tns:extends" />
					<element ref="tns:comment" />
					<any processContents="skip" namespace="##other" />
				</choice>
			</sequence>
			<attribute name="name" type="string"></attribute>
			<attribute name="familly" type="string"></attribute>
		</complexType>
	</element>

	<element name="property">
		<annotation>
				<documentation xml:lang="en">A JNDI proprierty.</documentation>
				<documentation xml:lang="fr">Propriété d'une ressource JNDI.</documentation>
		</annotation>
		<complexType>
			<attribute name="name" type="string"></attribute>
			<attribute name="value" type="string"></attribute>
		</complexType>
	</element>

	<element name="extends">
		<annotation>
				<documentation xml:lang="en">Propriary extenstions for a JNDI resource.</documentation>
				<documentation xml:lang="fr">Extension propriétaire d'une ressource JNDI.</documentation>
		</annotation>
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<any processContents="skip" />
			</sequence>
			<attribute name="appsrv" type="string"></attribute>
		</complexType>
	</element>

	<element name="comment" type="string" />

	<element name="attribute">
		<annotation>
				<documentation xml:lang="fr">Additional attributs in an extension.</documentation>
				<documentation xml:lang="fr">Attributs complémentaires dans une extension.</documentation>
		</annotation>
		<complexType>
			<simpleContent>
				<extension base="string">
					<attribute name="name" type="string"></attribute>
				</extension>
			</simpleContent>
		</complexType>
	</element>

</schema>

=== pprados/jndi-resources/jndi-resources/web-test/src/main/webapp/META-INF/jndi-resources.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
 * Copyright 2008 Philippe Prados.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
-->


<resources 
	xmlns="http://jndi-resources.googlecode.com/1.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jndi-resources.googlecode.com/1.0/ http://www.prados.fr/xsd/1.0/jndi-resources.xsd"
	id="jndi-web-test"
>

<!-- 
<comment>Custom application serveur</comment>
	<resource name="" familly="appsrv" >
		<extends appsrv="jboss3_x">
			<Connectors>
				<Connector port="8080"
					enableLookups="true">
				</Connector>
			</Connectors>
		</extends>
	</resource>
 -->
 
<!-- ******************************************************** --> 
<comment>JDBC</comment>
	<comment>Default</comment>
	<resource name="jndi-web-test/jdbc/MYDS" familly="jdbc/mydatasource" />

	<resource name="jndi-web-test/jdbc/Default" familly="jdbc/default" />

	<comment>HSQLDB</comment>
	<resource name="jndi-web-test/jdbc/HSQLDBMinimum" familly="jdbc/hsqldb" />

	<comment>MySQL</comment>
	<resource name="jndi-web-test/jdbc/MySQLNo" familly="jdbc/mysql" />
	<resource name="jndi-web-test/jdbc/MySQLXA" familly="jdbc/mysql">
		<property name="xa" value="yes"/>
	</resource>
	<resource name="jndi-web-test/jdbc/MySQLLocal" familly="jdbc/mysql">
		<property name="xa" value="local"/>
	</resource>

	<comment>Oracle</comment>
	<resource name="jndi-web-test/jdbc/OracleNo" familly="jdbc/oracle">
		<property name="artifact" value="ojdbc:ojdbc:14"/>
		<property name="connection-url" value="jdbc:oracle:thin:@${my.host}:1521:${my.oracle.sid}"/>
	</resource>

	<resource name="jndi-web-test/jdbc/OracleXA" familly="jdbc/oracle">
		<property name="xa" value="yes"/>
		<property name="host" value="LEHOST" />
	</resource>

	<resource name="jndi-web-test/jdbc/OracleLocal" familly="jdbc/oracle">
		<property name="xa" value="no"/>
		<extends appsrv="tomcat5_5">
			<attribute name="border">100</attribute>
		</extends>
		<extends appsrv="jboss3_x">
			<prepared-statement-cache-size>100</prepared-statement-cache-size>
		</extends>
	</resource>

	<resource name="jndi-web-test/jdbc/OracleSingle" familly="jdbc/oracle">
		<property name="xa" value="no"/>
		<property name="connection-url" value="jdbc:oracle:thin:@localhost:1521:XE"/>
		<property name="username" value="sa"/>
		<property name="password" value="password"/>
		<property name="min-pool-size" value="5"/>
		<property name="max-pool-size" value="20"/>
		<property name="prepared-statement-cache-size" value="32"/>
		<property name="validation-query" value="select 1 from dual"/>
	</resource>

	<resource name="jndi-web-test/jdbc/OracleMinimum" familly="jdbc/oracle" />

<!-- ******************************************************** --> 
<comment>Javamail</comment>
	<resource name="jndi-web-test/mail/default" familly="mail/default" />

	<resource name="jndi-web-test/mail/email" familly="mail/email">
 		<property name="email" value="${mon.e-mail}"/>
	</resource>

	<resource name="jndi-web-test/mail/set" familly="mail/default">
 		<property name="user" value="user@user.org"/>
 		<property name="password" value="password"/>
 		<property name="from" value="from@user.org"/>
 		<property name="host" value="smtp.pop3.host"/>
 		<property name="debug" value="true"/>
 		
 		<property name="store.protocol" value="pop3"/>
		<property name="store.host" value="pop3.host"/>
		<property name="store.port" value="1110"/>
		<property name="store.user" value="store@user.org"/>
		<property name="store.connectiontimeout" value="100"/>
		<property name="store.timeout" value="100"/>
		
		<property name="transport.protocol" value="smtp"/>
		<property name="transport.host" value="smtp.host"/>
		<property name="transport.port" value="1025"/>
		<property name="transport.user" value="transport@user.org"/>
		<property name="transport.connectiontimeout" value="100"/>
		<property name="transport.timeout" value="100"/>
		<extends appsrv="tomcat6_0">
			<attribute name="mail.smtp.user">moi@chezmoi.maison</attribute>
		</extends>
		<extends appsrv="jboss3_x">
			<attribute name="mail.smtp.user">moi@chezmoi.maison</attribute>
		</extends>
		
	</resource>

	<resource name="jndi-web-test/mail/imap" familly="mail/default">
 		<property name="store.protocol" value="imap"/>
 		<property name="transport.protocol" value="smtp"/>
	</resource>

	<resource name="jndi-web-test/mail/freeprotocol" familly="mail/default">
 		<property name="user" value="user@user.org"/>
 		<property name="from" value="from@user.org"/>
 		<property name="host" value="smtp.pop3.host"/>
 		<property name="debug" value="true"/>
 		
 		<property name="store.host" value="pop3.host"/>
		<property name="store.port" value="1110"/>
		<property name="store.user" value="store@user.org"/>
		<property name="store.connectiontimeout" value="100"/>
		<property name="store.timeout" value="100"/>
		
		<property name="transport.host" value="smtp.host"/>
		<property name="transport.port" value="1025"/>
		<property name="transport.user" value="transport@user.org"/>
		<property name="transport.connectiontimeout" value="100"/>
		<property name="transport.timeout" value="100"/>
	</resource>

<!-- ******************************************************** --> 
<comment>URL</comment>
	<resource name="jndi-web-test/url/properties" familly="url/default">
 		<property name="url" value="${url.default}"/>
	</resource>
	
<!-- ******************************************************** --> 
<comment>Host</comment>
	<resource name="jndi-web-test/host/srvname" familly="host/default">
 		<property name="host" value="${host.default}"/>
	</resource>

<!-- ******************************************************** --> 
<comment>Jms</comment>
	<resource name="jndi-web-test/jms/ConnectionFactory" familly="jms/default/cf"/>

	<resource name="jndi-web-test/jms/XAConnectionFactory" familly="jms/default/cf">
		<property name="xa" value="true"/>
	</resource>

	<resource name="jndi-web-test/jms/DeadLetterQueue" familly="jms/default/queue"/>
	<resource name="jndi-web-test/jms/ExpiryQueue" familly="jms/default/queue"/>

	<resource name="jndi-web-test/jms/Queue" familly="jms/default/queue"/>
	<resource name="jndi-web-test/jms/QueueSpecial" familly="jms/default/queue">
		<property name="dead-letter-queue" value="jndi-web-test/jms/DeadLetterQueue"/>
		<property name="expiry-queue" value="jndi-web-test/jms/ExpiryQueue"/>

	<property name="full-size" value="99999"/>
	<property name="redelivery-delay" value="9"/>
	<property name="message-counter-history-day-limit" value="9"/>
	
		<extends appsrv="jboss5_x-jms-srv">
			<attribute name="SecurityConfig">
				<security>
					<role name="guest" read="true" write="true" />
					<role name="publisher" read="true" write="true"
						create="false" />
					<role name="durpublisher" read="true" write="true"
						create="true" />
				</security>
			</attribute>
		</extends>
	</resource>
	
	<resource name="jndi-web-test/jms/Topic" familly="jms/default/topic"/>
	<resource name="jndi-web-test/jms/TopicSpecial" familly="jms/default/topic">
		<property name="dead-letter-queue" value="jndi-web-test/jms/DeadLetterQueue"/>
		<property name="expiry-queue" value="jndi-web-test/jms/ExpiryQueue"/>
		
		<property name="redelivery-delay" value="0"/>
		<property name="max-delivery-attempts" value="-1"/>
		<property name="max-size" value="-1"/>
		<property name="message-counter-history-day-limit" value="-1"/>
		<property name="preserve-ordering" value="false"/>
	</resource>

<!-- ******************************************************** --> 
<comment>Jndi</comment>
	<resource name="jndi-web-test/jndi/file" familly="jndi/file"/>
	<resource name="jndi-web-test/jndi/jboss" familly="jndi/jboss"/>
	<resource name="jndi-web-test/jndi/rmi" familly="jndi/rmi"/>
	<resource name="jndi-web-test/jndi/cos" familly="jndi/cos"/>
	<resource name="jndi-web-test/jndi/ldap" familly="jndi/ldap"/>
<!-- <resource name="jndi-web-test/jndi/dns" familly="jndi/dns"/>-->

<!-- ******************************************************** --> 
<comment>JAAS</comment>
	<resource name="jndi-web-test/jaas/default" familly="jaas/default" />

	<comment>internet</comment>
	<resource name="jndi-web-test/jaas/internet1" familly="jaas/internet" />
	<resource name="jndi-web-test/jaas/internet2" familly="jaas/internet" />

	<comment>intranet</comment>
	<resource name="jndi-web-test/jaas/intranet1" familly="jaas/intranet" />
 	<resource name="jndi-web-test/jaas/intranet2" familly="jaas/intranet" />

 	
</resources>

=== pprados/jndi-resources/trunk/jndi-resources/web-sample/src/main/webapp/META-INF/jndi-resources.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
 * Copyright 2008 Philippe Prados.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
-->

<resources 
	xmlns="http://jndi-resources.googlecode.com/1.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jndi-resources.googlecode.com/1.0/ http://www.prados.fr/xsd/1.0/jndi-resources.xsd"
	id="jndi-web-sample"
>
	<resource name="web-sample/jdbc/Default" familly="jdbc/default" />
	
	<resource name="web-sample/mail/Default" familly="mail/default" >
		<property name="store.protocol" value="imap"/>
		<property name="transport.protocol" value="smtp"/>
		<property name="transport.user" value="smtp@user.org"/>
	</resource>

	<resource name="web-sample/mail/email" familly="mail/email">
 		<property name="email" value="${mon.e-mail}"/>
	</resource>

	<resource name="web-sample/url/Default" familly="url/default">
 		<property name="url" value="${url.default}"/>
	</resource>

	<resource name="web-sample/host/Default" familly="host/default">
 		<property name="host" value="${host.default}"/>
	</resource>

	<resource name="web-sample/ejb/LookupJndi" familly="link/default">
 		<property name="link" value="ejb-sample/ejb/LookupJndi"/>
	</resource>

	<!-- Pour invoquer un EJB depuis un autre server --> 
	<!-- Parler des différentes stratégies avec schéma et target d'installation.
	Par exemple, un war et deux EAR avec des EJBs 
	partage d'un seul annuaire avec deux composants EAR dont un
	qui publie un EJB.
	
	Approche avec chaque composant ayant son annuaire, et récupération de l'un sur l'autre.
	Approche les deux composants dans le même servapp 
	 -->
	<resource name="web-sample/jndi/ejbs" familly="jndi/default"/>
	<resource name="ejb-sample/ejb/LookupJndi" familly="link/default">
 		<property name="link" value="java:web-sample/jndi/ejbs/ejb-sample/ejb/LookupJndi"/>
	</resource>
<!-- -->	

</resources>

=== pprados/jndi-resources/trunk/jndi-resources/ear-sample/src/main/applications/META-INF/jndi-resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * Copyright 2008 Philippe Prados.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
-->
<resources 
	xmlns="http://jndi-resources.googlecode.com/1.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jndi-resources.googlecode.com/1.0/ http://www.prados.fr/xsd/1.0/jndi-resources.xsd"
	id="ear-sample"
>
	<!-- *** WAR resources *** -->
	<resource name="web-sample/jdbc/Default" familly="jdbc/default" />
	
	<resource name="web-sample/mail/Default" familly="mail/default" >
		<property name="store.protocol" value="imap"/>
		<property name="transport.protocol" value="smtp"/>
		<property name="transport.user" value="smtp@user.org"/>
	</resource>

	<resource name="web-sample/mail/email" familly="mail/email">
 		<property name="email" value="${mon.e-mail}"/>
	</resource>

	<resource name="web-sample/url/Default" familly="url/default">
 		<property name="url" value="${url.default}"/>
	</resource>

	<resource name="web-sample/host/Default" familly="host/default">
 		<property name="host" value="${host.default}"/>
	</resource>

	<resource name="web-sample/ejb/LookupJndi" familly="link/default">
 		<property name="link" value="ejb-sample/ejb/LookupJndi"/>
	</resource>

	<!-- *** EJB resources (link to WAR resources) *** -->
	<resource name="ejb-sample/jdbc/Default" familly="link/default">
 		<property name="link" value="java:web-sample/jdbc/Default"/>
	</resource>

	<resource name="ejb-sample/url/Default" familly="link/default">
 		<property name="link" value="java:web-sample/url/Default"/>
	</resource>

	<resource name="ejb-sample/host/Default" familly="link/default">
 		<property name="link" value="java:web-sample/host/Default"/>
	</resource>

</resources>
